### ISSUE TITLE
Ubuntu 20 setup following the doc

### ISSUE THREAD

**Issue by gregtap** [szstonelee/redrock_old#1]
zlibstd-dev is present, yet we get:

```g++ -std=c++11 -c -o rocksdbapi.o rocksdbapi.cc -I ../deps/rocksdb/include
    LINK redis-server
g++: error: ../deps/staticlib/libz.a: No such file or directory
g++: error: ../deps/staticlib/libbz2.a: No such file or directory
g++: error: ../deps/staticlib/libsnappy.a: No such file or directory
g++: error: ../deps/staticlib/liblz4.a: No such file or directory
g++: error: ../deps/staticlib/libzstd.a: No such file or directory
```

**Comment by szstonelee** [comment]
These are the static compressed library files, i.e, *.a. 

RocksDB support compressed library and auto detect all of them and try to use them all. So I include all the compressed libraries of source files in deps folder. 

You can try to build them one by one in folder deps. After the building of all these lib, the static lib files need to be in deps/static/lib/ folder because RedRock link them statically.   

I tried to build them in the src/makefile. But I am not sure the makefile would work in all platforms. 

Check the following in src/makefile:

libz.a:
	cd ../deps/cd zlib-1.2.11 && ./configure && make && mv libz.a ../staticlib/

libbz2.a:
	cd ../deps && make bzip2 && mv bzip2/libbz2.a staticlib/

libsnappy.a:
	cd ../deps && make snappy

liblz4.a:
	cd ../deps && make lz4

libzstd.a:
	cd ../deps && make zstd
